/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import interfaces.UsuarioDAO;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import static sistemaconalep.Dashboard.labelDepartamento;
import controller.UsuarioDAOImpl;

/**
 *
 * @author Yair
 */
public class Usuarios extends javax.swing.JPanel {

    private int idUsuario = -1;
    /**
     * Creates new form Usaurios
     */
    public Usuarios() {
        initComponents();
        deshabilitarPanelNuevoUsuario();
        llenarTablaUsuarios();

    }

    //Metopo para deshabilitar PanelNuevoUsuario
    private void deshabilitarPanelNuevoUsuario() {
        Component[] componentes = panelActAddUsuario.getComponents();
        for (Component componente : componentes) {
            componente.setEnabled(false);
        }
    }

    //Método para habilitar panelNuevoUsuario
    private void habilitarPanelNuevoUsuario() {
        Component[] componentes = panelActAddUsuario.getComponents();
        for (Component componente : componentes) {
            componente.setEnabled(true);
        }
    }

    //llenar tabla Usuarios
    private static void llenarTablaUsuarios() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            List<Usuario> usuarios = new UsuarioDAOImpl().listar(labelDepartamento.getText());

            String[] columnas = {"ID", "Nombre(s)", "Apellidos", "Usuario", "Departamento", "Rol"};
            modelo.setColumnIdentifiers(columnas);

            for (Usuario usuario : usuarios) {
                String[] renglon = {String.valueOf(usuario.getIdUsuario()), usuario.getNombre(), usuario.getApellidos(), usuario.getUsuario(),
                    usuario.getDepartamento(), usuario.getRol()};
                modelo.addRow(renglon);
            }
            tablaUsuarios.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarios = new javax.swing.JPanel();
        etiUsuarios = new javax.swing.JLabel();
        panelActAddUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsuarioUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtClaveUsuario = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        boxRolUsuario = new javax.swing.JComboBox<>();
        btnAceptarActModUsuario = new javax.swing.JButton();
        btnNuevoUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        etiUsuarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etiUsuarios.setText("Usuarios");

        panelActAddUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setText("Nombre");

        txtNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel6.setText("Apellidos");

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel9.setText("Usuario");

        txtUsuarioUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel10.setText("Clave");

        txtClaveUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtClaveUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClaveUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel11.setText("Rol");

        boxRolUsuario.setBackground(new java.awt.Color(255, 255, 255));
        boxRolUsuario.setForeground(new java.awt.Color(0, 0, 0));
        boxRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador", "Admin" }));
        boxRolUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnAceptarActModUsuario.setBackground(new java.awt.Color(0, 126, 103));
        btnAceptarActModUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAceptarActModUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarActModUsuario.setText("Aceptar");
        btnAceptarActModUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 10, new java.awt.Color(0, 0, 0)));
        btnAceptarActModUsuario.setBorderPainted(false);
        btnAceptarActModUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptarActModUsuario.setFocusPainted(false);
        btnAceptarActModUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActModUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActAddUsuarioLayout = new javax.swing.GroupLayout(panelActAddUsuario);
        panelActAddUsuario.setLayout(panelActAddUsuarioLayout);
        panelActAddUsuarioLayout.setHorizontalGroup(
            panelActAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActAddUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActAddUsuarioLayout.createSequentialGroup()
                        .addComponent(txtClaveUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11))
                    .addGroup(panelActAddUsuarioLayout.createSequentialGroup()
                        .addComponent(txtNombreUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(boxRolUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addComponent(btnAceptarActModUsuario)
                .addContainerGap())
        );
        panelActAddUsuarioLayout.setVerticalGroup(
            panelActAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActAddUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarActModUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(panelActAddUsuarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelActAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtUsuarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(boxRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnNuevoUsuario.setBackground(new java.awt.Color(0, 126, 103));
        btnNuevoUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoUsuario.setText("Nuevo");
        btnNuevoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 10, new java.awt.Color(0, 0, 0)));
        btnNuevoUsuario.setBorderPainted(false);
        btnNuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoUsuario.setFocusPainted(false);
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });

        btnModificarUsuario.setBackground(new java.awt.Color(0, 126, 103));
        btnModificarUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnModificarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarUsuario.setText("Modificar");
        btnModificarUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 10, new java.awt.Color(0, 0, 0)));
        btnModificarUsuario.setBorderPainted(false);
        btnModificarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarUsuario.setFocusPainted(false);
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setBackground(new java.awt.Color(0, 126, 103));
        btnEliminarUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 10, new java.awt.Color(0, 0, 0)));
        btnEliminarUsuario.setBorderPainted(false);
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.setFocusPainted(false);
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelActAddUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiUsuarios)
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnNuevoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarUsuario))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiUsuarios)
                .addGap(27, 27, 27)
                .addComponent(panelActAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActModUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActModUsuarioActionPerformed
        String nombre = txtNombreUsuario.getText();
        String apellidos = txtApellidos.getText();
        String nusuario = txtUsuarioUsuario.getText();
        String clave = txtClaveUsuario.getText();
        String departamento = labelDepartamento.getText();
        String rol = boxRolUsuario.getSelectedItem().toString();

        if (nombre.trim().isEmpty() || apellidos.trim().isEmpty() || nusuario.trim().isEmpty()
                || clave.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos",
                    "AVISO", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Usuario usuario = new Usuario();
        usuario.setIdUsuario(idUsuario);
        usuario.setNombre(nombre);
        usuario.setApellidos(apellidos);
        usuario.setUsuario(nusuario);
        usuario.setClave(clave);
        usuario.setDepartamento(departamento);
        usuario.setRol(rol);

        try {
            UsuarioDAO usuarioDAO = new UsuarioDAOImpl();
            Usuario usuarioBuscado = usuarioDAO.traerUnUsuario(String.valueOf(idUsuario));
            if (usuarioBuscado.getIdUsuario() == 0) {
                usuarioDAO.registrar(usuario);
                JOptionPane.showMessageDialog(null, "Operación exitosa", "AVISO",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                usuarioDAO.modificar(usuario);
                JOptionPane.showMessageDialog(null, "Operación exitosa", "AVISO",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrió un error al realizar la opeación",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        llenarTablaUsuarios();
        txtNombreUsuario.setText("");
        txtApellidos.setText("");
        txtUsuarioUsuario.setText("");
        txtClaveUsuario.setText("");
        deshabilitarPanelNuevoUsuario();
        idUsuario = -1;
    }//GEN-LAST:event_btnAceptarActModUsuarioActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        habilitarPanelNuevoUsuario();
        txtNombreUsuario.setText("");
        txtApellidos.setText("");
        txtUsuarioUsuario.setText("");
        txtClaveUsuario.setText("");

    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        int fila = tablaUsuarios.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una fila para realizar la operación", "AVISO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String idUsuarioM = String.valueOf(tablaUsuarios.getValueAt(fila, 0));
        idUsuario = Integer.parseInt(idUsuarioM);
        UsuarioDAO usuarioDAO = new UsuarioDAOImpl();

        try {
            Usuario usuario = usuarioDAO.traerUnUsuario(idUsuarioM);
            txtNombreUsuario.setText(usuario.getNombre());
            txtApellidos.setText(usuario.getApellidos());
            txtUsuarioUsuario.setText(usuario.getUsuario());
            txtClaveUsuario.setText(usuario.getClave());
            boxRolUsuario.setSelectedItem(usuario.getRol());
        } catch (Exception e) {
            e.printStackTrace();
        }
        habilitarPanelNuevoUsuario();
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        int fila = tablaUsuarios.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una fila para realizar la operación",
                    "AVISO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(null, "Los registro seleccionados se eliminarán de forma definitiva\n¿Desea continuar?",
                "Confirmar eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {

            UsuarioDAO usuarioDAO = new UsuarioDAOImpl();

            for (int i : tablaUsuarios.getSelectedRows()) {
                try {
                    Usuario usuario = usuarioDAO.traerUnUsuario(String.valueOf(tablaUsuarios.getValueAt(i, 0)));
                    if (usuario.getRol().equalsIgnoreCase("Admin")) {
                        JOptionPane.showMessageDialog(null, "No se puede realizar la operación\n"
                                + "Un usuario de tipo administrador  no se puede eliminar", "AVISO", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    usuarioDAO.eliminar(String.valueOf(tablaUsuarios.getValueAt(i, 0)));
                    JOptionPane.showMessageDialog(null, "Operación exitosa", "AVISO", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            llenarTablaUsuarios();
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxRolUsuario;
    private javax.swing.JButton btnAceptarActModUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JLabel etiUsuarios;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelActAddUsuario;
    private javax.swing.JPanel panelUsuarios;
    public static javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtClaveUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtUsuarioUsuario;
    // End of variables declaration//GEN-END:variables
}
